- hosts: main
  roles:
    - role: users
      tags: users
      users: "{{ usersVars.list }}"

    - role: mc
      tags: mc

    - role: pip
      tags: pip

    - role: docker
      tags: docker
      packageUrlBase: "{{ dockerVars.packageUrlBase }}"
      packageFileName: "{{ dockerVars.packageFileName }}"

    - role: minio
      tags: minio
      accessKey: "{{ minioVars.accessKey }}"
      secretKey: "{{ minioVars.secretKey }}"
      buckets: "{{ minioVars.buckets }}"

    - role: gitlab
      tags: gitlab
      ports: "{{ gitlabVars.ports }}"
      baseDir: "{{ gitlabVars.baseDir }}"
      backup: "{{ gitlabVars.backup }}"
      baseUrl: "{{ gitlabVars.baseUrl }}"
      smtp: "{{ gitlabVars.smtp }}"
      additionalHostMachineHostnames: "{{ gitlabVars.additionalHostMachineHostnames }}"

    - role: backup-pruner
      tags: backup-pruner
      optimalCountConfig: "{{ backupPrunerVars.optimalCountConfig }}"
      storageType: "{{ backupPrunerVars.storageType }}"
      s3AccessKey: "{{ backupPrunerVars.s3AccessKey }}"
      s3SecretKey: "{{ backupPrunerVars.s3SecretKey }}"
      s3Bucket: "{{ backupPrunerVars.s3Bucket }}"
      scanInterval: "{{ backupPrunerVars.scanInterval }}"
      sendEmail: "{{ backupPrunerVars.sendEmail }}"
      longestDelayBetweenEmails: "{{ backupPrunerVars.longestDelayBetweenEmails }}"
      smtpHostname: "{{ backupPrunerVars.smtpHostname }}"
      smtpPort: "{{ backupPrunerVars.smtpPort }}"
      smtpDomain: "{{ backupPrunerVars.smtpDomain }}"
      smtpUser: "{{ backupPrunerVars.smtpUser }}"
      smtpPassword: "{{ backupPrunerVars.smtpPassword }}"
      smtpEnableSsl: "{{ backupPrunerVars.smtpEnableSsl }}"
      emailFrom: "{{ backupPrunerVars.emailFrom }}"
      emailTo: "{{ backupPrunerVars.emailTo }}"
      emailSubject: "{{ backupPrunerVars.emailSubject }}"
      doPrune: "{{ backupPrunerVars.doPrune }}"

    - role: apache
      tags: apache
      directories: "{{ apacheVars.directories }}"

    - role: jenkins
      tags: jenkins
      jenkinsUsername: "{{ jenkinsVars.jenkinsUsername }}"
      jenkinsPassword: "{{ jenkinsVars.jenkinsPassword }}"
      credentials: "{{ jenkinsVars.credentials }}"
      projects: "{{ jenkinsVars.projects }}"
      ports: "{{ jenkinsVars.ports }}"
      volumes: "{{ jenkinsVars.volumes }}"

    - role: mail
      tags: mail
      sslSmtpClientPort: "{{ mailVars.sslSmtpClientPort }}"
      sslImapPort: "{{ mailVars.sslImapPort }}"
      smtpOtherMailServersPort: "{{ mailVars.smtpOtherMailServersPort }}"
      accounts: "{{ mailVars.accounts }}"
      hostname: "{{ mailVars.hostname }}"
      domainname: "{{ mailVars.domainname }}"
      adminUser: "{{ mailVars.adminUser }}"

    - role: proxy
      tags: proxy
      proxyHttpsPort: "{{ proxyVars.proxyHttpsPort }}"
      servers: "{{ proxyVars.servers }}"

  vars_files:
    - "{{ varsDirectory }}/jenkinsVars.yml"
    - "{{ varsDirectory }}/usersVars.yml"
    - "{{ varsDirectory }}/apacheVars.yml"
    - "{{ varsDirectory }}/dockerVars.yml"
    - "{{ varsDirectory }}/minioVars.yml"
    - "{{ varsDirectory }}/gitlabVars.yml"
    - "{{ varsDirectory }}/backupPrunerVars.yml"
    - "{{ varsDirectory }}/mailVars.yml"
    - "{{ varsDirectory }}/proxyVars.yml"